USE [inventory]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SecondaryCustomer](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[CompanyCode] [nvarchar](40) NOT NULL,
	[CustomerCode] [nvarchar](40) NOT NULL,
	[SecondaryCustomerCode] [nvarchar](40) NOT NULL,
	[SecondaryCustomerName] [nvarchar](255) ,
	[SecondaryCustomerName2] [nvarchar](255),
	[LegalOwnerName] [nvarchar](255),
	[ReferenceSecondaryCustomerCode] [nvarchar](40) ,
	[ParentSecondaryCustomerCode][nvarchar](40),
	[ContactName] [nvarchar](255),
	[Gender] [nvarchar](1),
	[DateOfBirth] [date] null,
	[GivenName] [nvarchar] (255),
	[Surname] [nvarchar] (255),
	[IdentityCard] [nvarchar] (40),
	[TaxType] [nvarchar] (40),
	[TaxCode] [nvarchar] (120),
	[Tax] [nvarchar] (120),
	[Email] [nvarchar] (225),
	[Phone] [nvarchar] (80),
	[Phone2] [nvarchar] (80),
	[Address] [nvarchar] (500),
	[Address2] [nvarchar] (500),
	[Address3] [nvarchar] (500),
	[Country] [nvarchar] (500),
	[State] [nvarchar] (500),
	[City] [nvarchar] (500),
	[PostCode] [nvarchar] (40),
	[Club] [nvarchar] (255),
	[AnchorAccount] [nvarchar] (40),
	[EnviromentallyConscious] [nvarchar] (500),
	[RegionCode] [nvarchar] (40),
	[RegionL1] [nvarchar] (40),
	[RegionL2] [nvarchar] (40),
	[RegionL3] [nvarchar] (40),
	[RegionL4] [nvarchar] (40),
	[RegionL5] [nvarchar] (40),
	[HierarchyCode] [nvarchar] (40),
	[HierarchyL01] [nvarchar] (40),
	[HierarchyL02] [nvarchar] (40),
	[HierarchyL03] [nvarchar] (40),
	[ShipToAddress] [nvarchar] (500),
	[ShipToAddress2] [nvarchar] (500),
	[ShipToPhone] [nvarchar] (40),
	[PaymentTerm] [nvarchar] (40),
	[CreditDay] [int] null,
	[Latitude] [decimal] null,
	[Longitude] [decimal] null,
	[CreditLimit] [decimal] null,
	[BankCode] [nvarchar] (40),
	[BankName] [nvarchar] (255),
	[BankAddress] [nvarchar] (255),
	[BankAccount] [nvarchar] (80),
	[BankAccountName] [nvarchar] (120),
	[SecondaryCustomerGroup] [nvarchar] (40),
	[SecondaryCustomerClass] [nvarchar] (40),
	[Attribute1] [nvarchar] (255),
	[Attribute2] [nvarchar] (255),
	[Remark] [nvarchar] (2000),
	[Status] [nvarchar] (40),
	[SystemStatus] [nvarchar] (40),
	[DefaultDeliveryDay] [int],
	[ContractExpiredDate] [datetime],
	[Title] [nvarchar] (255),
	[CustomerSegment] [nvarchar] (40),
	[SecondaryCustomerType] [nvarchar] (40),
	[BankBrandName] [nvarchar] (120),
	[BankBrandCode] [nvarchar] (120),
	[IdentityCardDate] [datetime] null,
	[IdentityCardPlace] [nvarchar] (40),
	[Source] [nvarchar] (1 ),
	[createdBy] [nvarchar] (255) null,
	[createdDateTime] [datetime] null,
	[lastUpdatedBy] [nvarchar] (255) null,
	[lastUpdatedDateTime] [datetime] null,
	[rowNumber] [timestamp] null,
	[Attribute3] [nvarchar] (255),
	[Attribute4] [nvarchar] (255),
	[Attribute5] [nvarchar] (255),
	[PaymentTermDescription] [nvarchar] (500),
	[PaymentMethod] [nvarchar] (40),
	[PaymentMethodDescription] [nvarchar] (500),
	[SecondaryCustomerCategory] [nvarchar] (40),
	[PricePaymentTerm] [nvarchar] (40),
	[Attribute6] [nvarchar] (40),
	[BillToSecondaryCustomerCode] [nvarchar] (40),
	[VATRegistrationID] [nvarchar] (40),
	[SecondaryCustomerTypeDescription] [nvarchar] (255),
	[SecondaryCustomerClassDescription] [nvarchar] (255),
	[CustomerSegmentDescription] [nvarchar] (255),
	[ParentSecondaryCustomerCodeDescription] [nvarchar] (255),
	[Attribute7] [nvarchar] (40),
	[BillToSecondaryCustomerName] [nvarchar] (255),
	[BusinessType] [nvarchar] (40),
	[SecondaryCustomerNameInvoice] [nvarchar] (255),
	[ImageSecondarycustomer] [image] ,
	[Deleted] [bit] null,
	[PricePaymentTermCode] [nvarchar] (255),
 PRIMARY KEY CLUSTERED
(
  [id] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO SecondaryCustomer([CompanyCode],[CustomerCode],[SecondaryCustomerCode],[SecondaryCustomerName], [Address], [Attribute1],[Attribute2],[Attribute3],[Attribute4],[Attribute5],[Status],[Deleted])
Values 
('1','1','1','1','1','1','1','1','1','1','I',0),
('2','2','2','2','2','2','2','2','2','2','I',0),
('2','2','2','2','2','2','2','2','2','2','new',0),
('2','2','2','2','2','2','2','2','2','2','new',0)
ALTER TABLE [dbo].[SecondaryCustomer] ADD  DEFAULT (getdate()) FOR [DateOfBirth]
GO