import { SecondaryCustomer } from '@app/@core/data/se-customer';
import { EntityState, EntityAdapter, createEntityAdapter } from '@ngrx/entity';

export interface SecondaryCustomerState extends EntityState<SecondaryCustomer> {
    selectedSecondaryCustomerID: number | null;
}
export const secondarycustomerAdapter: EntityAdapter<SecondaryCustomer> = createEntityAdapter<SecondaryCustomer>({
    selectId: (secondarycustomer: SecondaryCustomer) => secondarycustomer.id,
    sortComparer: false,
});
export const secondarycustomerInitialState: SecondaryCustomerState = secondarycustomerAdapter.getInitialState({
    selectedSecondaryCustomerID: null,
    entities: {
        0: {
            id: 0,
            companyCode: '',
            customerCode: '',
            secondaryCustomerCode: '',
            secondaryCustomerName: '',
            secondaryCustomerName2: '',
            legalOwnerName: '',
            referenceSecondaryCustomerCode: '',
            parentSecondaryCustomerCode: '',
            contactName: '',
            gender: '',
            dateOfBirth: null,
            givenName: '',
            surname: '',
            identityCard: '',
            taxType: '',
            taxCode: '',
            fax: '',
            email: '',
            phone: '',
            phone2: '',
            address: '',
            address2: '',
            address3: '',
            country: '',
            state: '',
            city: '',
            postCode: '',
            club: '',
            anchorAccount: '',
            enviromentallyConscious: '',
            regionCode: '',
            regionL1: '',
            regionL2: '',
            regionL3: '',
            regionL4: '',
            regionL5: '',
            hierarchyCode: '',
            hierarchyL01: '',
            hierarchyL02: '',
            hierarchyL03: '',
            shipToAddress: '',
            shipToAddress2: '',
            shipToPhone: '',
            paymentTerm: '',
            latitude: null,
            longitude: null,
            creditLimit: null,
            bankCode: '',
            bankName: '',
            bankAddress: '',
            bankAccount: '',
            bankAccountName: '',
            secondaryCustomerGroup: '',
            secondaryCustomerClass: '',
            attribute1: '',
            attribute2: '',
            remark: '',
            status: '',
            systemStatus: '',
            defaultDeliveryDay: 0,
            contractExpiredDate: null,
            title: '',
            customerSegment: '',
            secondaryCustomerType: '',
            bankBrandName: '',
            bankBrandCode: '',
            identityCardDate: null,
            identityCardPlace: '',
            source: '',
            createdBy: '',
            createdDateTime: '',
            rowVersion: '',
            attribute3: '',
            attribute4: '',
            attribute5: '',
            paymentTermDescription: '',
            paymentMethod: '',
            paymentMethodDescription: '',
            secondaryCustomerCategory: '',
            pricePaymentTerm: '',
            attribute6: '',
            billToSecondaryCustomerCode: '',
            vatregistrationId: '',
            secondaryCustomerTypeDescription: '',
            secondaryCustomerClassDescription: '',
            customerSegmentDescription: '',
            secondaryCustomerGroupDescription: '',
            parentSecondaryCustomerCodeDescription: '',
            attribute7: '',
            billToSecondaryCustomerName: '',
            businessType: '',
            secondaryCustomerNameInvoice: '',
            rowNumber: null,
            tax: '',
            creditDay: 0,
            lastUpdatedBy: '',
            lastUpdatedDateTime: null,
            pricePaymentTermCode: null,
            deleted: false,
            imageSecondarycustomer: {
                thumbnail: '',
                smallThumbnail: '',
            },
        },
    }
});
